### ISSUE TITLE
Remove payload requirements

### ISSUE THREAD

**Issue by theEpsilon** [mindtastic/bouncer#24]
Currently, there are mandatory request parameters required by requests to the bouncer proxy that should be omitted.

**GET /self-service/registration/\***
- [ ] Remove requirement for JSON payload: `{}`

**POST /self-service/registration/\***
- [ ] Remove requirement for JSON payload: `{"method": "password"}`
- [ ] Remove requirement for Header `Content-Type: application/json`

**Comment by ldb** [comment]
Already fixed by #23
